#   Target
PROGRAM_spu := ex1_spu
LIBRARY_embed := lib_ex1_spu.a

# include partea care face toata treaba pe baza definitiilor de mai sus

ifdef CELL_TOP
            include $(CELL_TOP)/buildutils/make.footer
else
            include ../../../../buildutils/make.footer
endif
